# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

x-base-service: &base-service
  image: bogart-bot:latest
  restart: unless-stopped
  env_file:
    - .env
  volumes:
    - ./data/quotes.yaml:/app/data/quotes.yaml:ro
    - /etc/localtime:/etc/localtime:ro
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL
  cap_add:
    - SETGID
    - SETUID
  read_only: true
  tmpfs:
    - /tmp:rw,noexec,nosuid,size=100m

services:
  bogart-bot:
    <<: *base-service
    container_name: bogart-bot-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - ENABLE_METRICS=true
      - QUOTES_FILE=/app/data/quotes.yaml
    volumes:
      - ./data/quotes.yaml:/app/data/quotes.yaml:ro
      - bogart-prod-logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot health check - OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - bogart-prod-network



volumes:
  bogart-prod-logs:
    driver: local

networks:
  bogart-prod-network:
    driver: bridge