# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

x-base-service: &base-service
  image: bogart-bot:latest
  restart: unless-stopped
  env_file:
    - .env
  volumes:
    - ./data/quotes.yaml:/app/data/quotes.yaml:ro
    - /etc/localtime:/etc/localtime:ro
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL
  cap_add:
    - SETGID
    - SETUID
  read_only: true
  tmpfs:
    - /tmp:rw,noexec,nosuid,size=100m

services:
  bogart-bot:
    <<: *base-service
    container_name: bogart-bot-small-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      cache_from:
        - node:18-slim
        - bogart-bot:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - NODE_ENV=production
      - ENABLE_METRICS=true
      - QUOTES_FILE=/app/data/quotes.yaml
    volumes:
      - ./data/quotes.yaml:/app/data/quotes.yaml:ro
      - bogart-prod-data:/app/data:rw
      - bogart-prod-logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot health check - OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - bogart-prod-network



volumes:
  bogart-prod-data:
    driver: local
  bogart-prod-logs:
    driver: local

networks:
  bogart-prod-network:
    driver: bridge